import = [
    "~/.config/alacritty/themes/themes/github_light.toml"
]

[window]
opacity = 1.0
padding = { x = 10, y = 2 }

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }